# Generated by Django 4.2.16 on 2024-10-23 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='linkedin',
            field=models.URLField(default='www.linkedin.com', verbose_name='Фейсбук'),
        ),
        migrations.AlterField(
            model_name='info',
            name='twitter',
            field=models.URLField(default='www.twitter.com', verbose_name='ТикТок'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True, verbose_name='Фейсбук url'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='twitter_url',
            field=models.URLField(blank=True, null=True, verbose_name='ТикТок url'),
        ),
    ]
