# Generated by Django 5.1.1 on 2024-09-08 04:03

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_banner_aboutus_about_us_ru_aboutus_about_us_uz_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=150, verbose_name='Полное имя')),
                ('full_name_uz', models.CharField(max_length=150, null=True, verbose_name='Полное имя')),
                ('full_name_ru', models.CharField(max_length=150, null=True, verbose_name='Полное имя')),
                ('position', models.CharField(max_length=50, verbose_name='Позиция')),
                ('position_uz', models.CharField(max_length=50, null=True, verbose_name='Позиция')),
                ('position_ru', models.CharField(max_length=50, null=True, verbose_name='Позиция')),
                ('image', models.ImageField(upload_to='time/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команды',
                'ordering': ('created_at',),
            },
        ),
        migrations.DeleteModel(
            name='Time',
        ),
        migrations.AlterModelOptions(
            name='aboutus',
            options={'ordering': ('created_at',), 'verbose_name': 'О нас', 'verbose_name_plural': 'О нас'},
        ),
        migrations.AlterModelOptions(
            name='additionallinks',
            options={'ordering': ('created_at',), 'verbose_name': 'Дополнительная ссылка', 'verbose_name_plural': 'Дополнительные ссылки'},
        ),
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ('created_at',), 'verbose_name': 'Баннер', 'verbose_name_plural': 'Баннеры'},
        ),
        migrations.AlterModelOptions(
            name='customeropinion',
            options={'ordering': ('created_at',), 'verbose_name': 'Мнение клиента', 'verbose_name_plural': 'Мнения клиентов'},
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ('created_at',), 'verbose_name': 'Часто задаваемый вопрос', 'verbose_name_plural': 'Часто задаваемые вопросы'},
        ),
        migrations.AlterModelOptions(
            name='info',
            options={'ordering': ('created_at',), 'verbose_name': 'Информация', 'verbose_name_plural': 'Информации'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('created_at',), 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterModelOptions(
            name='officeaddress',
            options={'ordering': ('created_at',), 'verbose_name': 'Адрес офиса', 'verbose_name_plural': 'Адреса офисов'},
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'ordering': ('created_at',), 'verbose_name': 'Сервис', 'verbose_name_plural': 'Сервисы'},
        ),
        migrations.AlterModelOptions(
            name='servicescategory',
            options={'ordering': ('created_at',), 'verbose_name': 'Категория сервиса', 'verbose_name_plural': 'Категории сервисов'},
        ),
        migrations.AlterModelOptions(
            name='statistics',
            options={'ordering': ('created_at',), 'verbose_name': 'Статистика', 'verbose_name_plural': 'Статистики'},
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='about_us',
            field=ckeditor.fields.RichTextField(verbose_name='О нас'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='about_us_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='О нас'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='about_us_uz',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='О нас'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='image',
            field=models.ImageField(upload_to='about/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='our_goal',
            field=models.TextField(max_length=500, verbose_name='Наши цели'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='our_goal_ru',
            field=models.TextField(max_length=500, null=True, verbose_name='Наши цели'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='our_goal_uz',
            field=models.TextField(max_length=500, null=True, verbose_name='Наши цели'),
        ),
        migrations.AlterField(
            model_name='additionallinks',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='additionallinks',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='additionallinks',
            name='name_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='additionallinks',
            name='name_uz',
            field=models.CharField(max_length=150, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='additionallinks',
            name='url',
            field=models.URLField(verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(upload_to='banners/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='text',
            field=models.CharField(max_length=150, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='text_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='text_uz',
            field=models.CharField(max_length=150, null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='customeropinion',
            name='company_name',
            field=models.CharField(max_length=100, verbose_name='Название компании'),
        ),
        migrations.AlterField(
            model_name='customeropinion',
            name='company_name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Название компании'),
        ),
        migrations.AlterField(
            model_name='customeropinion',
            name='company_name_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Название компании'),
        ),
        migrations.AlterField(
            model_name='customeropinion',
            name='full_name',
            field=models.CharField(max_length=150, verbose_name='Полное имя'),
        ),
        migrations.AlterField(
            model_name='customeropinion',
            name='full_name_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Полное имя'),
        ),
        migrations.AlterField(
            model_name='customeropinion',
            name='full_name_uz',
            field=models.CharField(max_length=150, null=True, verbose_name='Полное имя'),
        ),
        migrations.AlterField(
            model_name='customeropinion',
            name='opinion',
            field=models.CharField(max_length=150, verbose_name='Мнение'),
        ),
        migrations.AlterField(
            model_name='customeropinion',
            name='opinion_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Мнение'),
        ),
        migrations.AlterField(
            model_name='customeropinion',
            name='opinion_uz',
            field=models.CharField(max_length=150, null=True, verbose_name='Мнение'),
        ),
        migrations.AlterField(
            model_name='customeropinion',
            name='position',
            field=models.CharField(max_length=50, verbose_name='Позиция'),
        ),
        migrations.AlterField(
            model_name='customeropinion',
            name='position_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Позиция'),
        ),
        migrations.AlterField(
            model_name='customeropinion',
            name='position_uz',
            field=models.CharField(max_length=50, null=True, verbose_name='Позиция'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.CharField(max_length=1000, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer_ru',
            field=models.CharField(max_length=1000, null=True, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer_uz',
            field=models.CharField(max_length=1000, null=True, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.CharField(max_length=150, verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question_uz',
            field=models.CharField(max_length=150, null=True, verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='info',
            name='instagram',
            field=models.URLField(default='www.instagram.com', verbose_name='Инстаграм'),
        ),
        migrations.AlterField(
            model_name='info',
            name='linkedin',
            field=models.URLField(default='www.linkedin.com', verbose_name='Линкедин'),
        ),
        migrations.AlterField(
            model_name='info',
            name='phone_number',
            field=models.CharField(max_length=50, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='info',
            name='telegram',
            field=models.URLField(default='www.telegram.com', verbose_name='Телеграм'),
        ),
        migrations.AlterField(
            model_name='info',
            name='twitter',
            field=models.URLField(default='www.twitter.com', verbose_name='Твиттер'),
        ),
        migrations.AlterField(
            model_name='info',
            name='youtube',
            field=models.URLField(default='www.youtube.com', verbose_name='Ютуб'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content_uz',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(upload_to='news/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='news',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='news',
            name='short_description',
            field=models.CharField(max_length=150, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='news',
            name='short_description_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='news',
            name='short_description_uz',
            field=models.CharField(max_length=150, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='news',
            name='views_count',
            field=models.IntegerField(default=0, verbose_name='Количество просмотров'),
        ),
        migrations.AlterField(
            model_name='officeaddress',
            name='address_name',
            field=models.CharField(max_length=250, verbose_name='Название адреса'),
        ),
        migrations.AlterField(
            model_name='officeaddress',
            name='address_name_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='Название адреса'),
        ),
        migrations.AlterField(
            model_name='officeaddress',
            name='address_name_uz',
            field=models.CharField(max_length=250, null=True, verbose_name='Название адреса'),
        ),
        migrations.AlterField(
            model_name='officeaddress',
            name='info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='office_address', to='base.info', verbose_name='Информация'),
        ),
        migrations.AlterField(
            model_name='officeaddress',
            name='latitude',
            field=models.FloatField(verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='officeaddress',
            name='longitude',
            field=models.FloatField(verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='officeaddress',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='services',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.servicescategory', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='services',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='services',
            name='content_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='services',
            name='content_uz',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='services',
            name='image',
            field=models.ImageField(upload_to='services/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='services',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='services',
            name='name_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='services',
            name='name_uz',
            field=models.CharField(max_length=150, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='servicescategory',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='servicescategory',
            name='name_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='servicescategory',
            name='name_uz',
            field=models.CharField(max_length=150, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='customers_number',
            field=models.PositiveIntegerField(verbose_name='Количество клиентов'),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='service_indicator',
            field=models.PositiveIntegerField(verbose_name='Индикатор обслуживания'),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='services_number',
            field=models.PositiveIntegerField(verbose_name='Количество сервисов'),
        ),
    ]
