# Generated by Django 4.2.16 on 2024-10-24 15:07

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_info_linkedin_alter_info_twitter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=ckeditor.fields.RichTextField(verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer_uz',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.TextField(max_length=1000, verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question_en',
            field=models.TextField(max_length=1000, null=True, verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question_ru',
            field=models.TextField(max_length=1000, null=True, verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question_uz',
            field=models.TextField(max_length=1000, null=True, verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='news',
            name='short_description',
            field=models.TextField(max_length=350, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='news',
            name='short_description_en',
            field=models.TextField(max_length=350, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='news',
            name='short_description_ru',
            field=models.TextField(max_length=350, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='news',
            name='short_description_uz',
            field=models.TextField(max_length=350, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.TextField(max_length=250, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_en',
            field=models.TextField(max_length=250, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_ru',
            field=models.TextField(max_length=250, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_uz',
            field=models.TextField(max_length=250, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='name',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='название проекта'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='name_en',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='название проекта'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='name_ru',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='название проекта'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='name_uz',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='название проекта'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='short_description',
            field=models.TextField(max_length=350, verbose_name='краткое описание'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='short_description_en',
            field=models.TextField(max_length=350, null=True, verbose_name='краткое описание'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='short_description_ru',
            field=models.TextField(max_length=350, null=True, verbose_name='краткое описание'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='short_description_uz',
            field=models.TextField(max_length=350, null=True, verbose_name='краткое описание'),
        ),
    ]
