# Generated by Django 5.1.1 on 2024-09-09 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_customeropinion_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeropinion',
            name='opinion',
            field=models.TextField(max_length=800, verbose_name='Мнение'),
        ),
        migrations.AlterField(
            model_name='customeropinion',
            name='opinion_ru',
            field=models.TextField(max_length=800, null=True, verbose_name='Мнение'),
        ),
        migrations.AlterField(
            model_name='customeropinion',
            name='opinion_uz',
            field=models.TextField(max_length=800, null=True, verbose_name='Мнение'),
        ),
        migrations.AlterField(
            model_name='customeropinion',
            name='position',
            field=models.CharField(max_length=150, verbose_name='Позиция'),
        ),
        migrations.AlterField(
            model_name='customeropinion',
            name='position_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Позиция'),
        ),
        migrations.AlterField(
            model_name='customeropinion',
            name='position_uz',
            field=models.CharField(max_length=150, null=True, verbose_name='Позиция'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(max_length=1000, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer_ru',
            field=models.TextField(max_length=1000, null=True, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer_uz',
            field=models.TextField(max_length=1000, null=True, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.TextField(max_length=500, verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question_ru',
            field=models.TextField(max_length=500, null=True, verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question_uz',
            field=models.TextField(max_length=500, null=True, verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='news',
            name='short_description',
            field=models.CharField(max_length=255, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='news',
            name='short_description_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='news',
            name='short_description_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_uz',
            field=models.CharField(max_length=150, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='team',
            name='position',
            field=models.CharField(max_length=255, verbose_name='Позиция'),
        ),
        migrations.AlterField(
            model_name='team',
            name='position_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Позиция'),
        ),
        migrations.AlterField(
            model_name='team',
            name='position_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Позиция'),
        ),
    ]
