# Generated by Django 5.0.9 on 2024-10-01 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_customeropinion_opinion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=150, verbose_name='Полное имя')),
                ('full_name_uz', models.CharField(max_length=150, null=True, verbose_name='Полное имя')),
                ('full_name_ru', models.CharField(max_length=150, null=True, verbose_name='Полное имя')),
                ('position', models.CharField(max_length=255, verbose_name='Позиция')),
                ('position_uz', models.CharField(max_length=255, null=True, verbose_name='Позиция')),
                ('position_ru', models.CharField(max_length=255, null=True, verbose_name='Позиция')),
                ('image', models.ImageField(upload_to='partner/', verbose_name='Изображение')),
                ('category', models.IntegerField(choices=[(1, 'Юристы'), (2, 'Натарус'), (3, 'Аудиторы')], default=1)),
            ],
            options={
                'verbose_name': 'Партнер',
                'verbose_name_plural': 'Партнеры',
                'ordering': ('created_at',),
            },
        ),
        migrations.AlterField(
            model_name='customeropinion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='customer_opinion/', verbose_name='Изображение'),
        ),
    ]
