# Generated by Django 5.0.9 on 2024-10-01 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_customeropinion_opinion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeropinion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='customer_opinion/', verbose_name='Изображение'),
        ),
    ]
