# Generated by Django 5.0.9 on 2024-10-01 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_partners'),
    ]

    operations = [
        migrations.AddField(
            model_name='partners',
            name='full_name_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Полное имя'),
        ),
        migrations.AddField(
            model_name='partners',
            name='full_name_uz',
            field=models.CharField(max_length=150, null=True, verbose_name='Полное имя'),
        ),
        migrations.AddField(
            model_name='partners',
            name='position_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Позиция'),
        ),
        migrations.AddField(
            model_name='partners',
            name='position_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Позиция'),
        ),
    ]
