# Generated by Django 5.0.9 on 2024-10-11 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_faqcategory_remove_customeropinion_company_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partners',
            name='category',
        ),
        migrations.RemoveField(
            model_name='partners',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='partners',
            name='full_name_en',
        ),
        migrations.RemoveField(
            model_name='partners',
            name='full_name_ru',
        ),
        migrations.RemoveField(
            model_name='partners',
            name='full_name_uz',
        ),
        migrations.RemoveField(
            model_name='partners',
            name='position',
        ),
        migrations.RemoveField(
            model_name='partners',
            name='position_en',
        ),
        migrations.RemoveField(
            model_name='partners',
            name='position_ru',
        ),
        migrations.RemoveField(
            model_name='partners',
            name='position_uz',
        ),
        migrations.AddField(
            model_name='partners',
            name='company_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Название компании'),
        ),
        migrations.AddField(
            model_name='partners',
            name='company_name_en',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Название компании'),
        ),
        migrations.AddField(
            model_name='partners',
            name='company_name_ru',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Название компании'),
        ),
        migrations.AddField(
            model_name='partners',
            name='company_name_uz',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Название компании'),
        ),
    ]
