# Generated by Django 5.0.9 on 2024-10-11 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_partners_category_remove_partners_full_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('short_description', models.CharField(max_length=255, verbose_name='краткое описание')),
                ('short_description_uz', models.CharField(max_length=255, null=True, verbose_name='краткое описание')),
                ('short_description_ru', models.CharField(max_length=255, null=True, verbose_name='краткое описание')),
                ('short_description_en', models.CharField(max_length=255, null=True, verbose_name='краткое описание')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('short_description', models.CharField(max_length=255, verbose_name='краткое описание')),
                ('short_description_uz', models.CharField(max_length=255, null=True, verbose_name='краткое описание')),
                ('short_description_ru', models.CharField(max_length=255, null=True, verbose_name='краткое описание')),
                ('short_description_en', models.CharField(max_length=255, null=True, verbose_name='краткое описание')),
                ('image', models.ImageField(upload_to='project/', verbose_name='изображение')),
                ('youtube_url', models.URLField(blank=True, null=True)),
                ('telegram_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('website_url', models.URLField(blank=True, null=True)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AchievementsImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='achievements/')),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.achievements')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
