# Generated by Django 5.0.9 on 2024-10-11 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_achievements_projects_achievementsimages'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualWebsite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_link', models.URLField()),
            ],
        ),
    ]
