# Generated by Django 5.0.9 on 2024-10-11 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_manualwebsite_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeropinion',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='customer_opinion/', verbose_name='Видео'),
        ),
    ]
