# Generated by Django 5.0.9 on 2024-10-11 23:06

import base.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_customeropinion_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeropinion',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='customer_opinion/', validators=[base.utils.validate_video_file], verbose_name='Видео'),
        ),
    ]
