# Generated by Django 5.0.9 on 2024-10-14 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_projects_name_en_projects_name_ru_projects_name_uz'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualwebsite',
            name='youtube_link_en',
            field=models.URLField(null=True, verbose_name='Ютуб видео ссылка'),
        ),
        migrations.AddField(
            model_name='manualwebsite',
            name='youtube_link_ru',
            field=models.URLField(null=True, verbose_name='Ютуб видео ссылка'),
        ),
        migrations.AddField(
            model_name='manualwebsite',
            name='youtube_link_uz',
            field=models.URLField(null=True, verbose_name='Ютуб видео ссылка'),
        ),
    ]
