# Generated by Django 5.1.1 on 2024-09-07 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category_name', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MeetingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_number', models.CharField(blank=True, max_length=150, null=True)),
                ('customer_full_name', models.CharField(max_length=150)),
                ('customer_phone', models.CharField(max_length=20)),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('meeting_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('meeting_status', models.IntegerField(choices=[(0, 'ОЖИДАЕТСЯ ПЛАТЕЖ'), (1, 'ПРИНЯТ'), (2, 'ЗАВЕРШЕННЫЙ'), (3, 'ОТМЕНЕНО')], default=0)),
                ('meeting_type', models.IntegerField(choices=[(0, 'ЗВОНОК'), (1, 'ВИДЕО ЗВОНОК'), (2, 'ВСТРЕЧА')])),
                ('meeting_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('message', models.TextField(max_length=1000)),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='serviceses.documentcategory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_name', models.CharField(max_length=150)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('document_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviceses.documentcategory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_number', models.CharField(blank=True, max_length=150, null=True)),
                ('customer_full_name', models.CharField(max_length=250)),
                ('customer_phone', models.CharField(max_length=20)),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('customer_message', models.TextField(max_length=1000)),
                ('status', models.IntegerField(choices=[(0, 'ОЖИДАЕТСЯ ПЛАТЕЖ'), (1, 'ДОКУМЕНТ ПРИНЯТ'), (2, 'РАССМАТРИВАЕТЬСЯ'), (3, 'ЗАВЕРШЕННЫЙ'), (4, 'ОТМЕНЕНО')], default=0)),
                ('document_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='serviceses.documentcategory')),
                ('document_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='serviceses.documenttype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
