# Generated by Django 5.0.9 on 2024-10-15 12:45

import datetime
import django.db.models.deletion
import serviceses.models
import serviceses.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=150, verbose_name='Полное имя')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Электронная почьта')),
                ('phone', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тип')),
                ('message', models.TextField(max_length=1000, verbose_name='Сообщение')),
                ('file', models.FileField(blank=True, null=True, upload_to='contacts/document/', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='DocumentOrderPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Страница заказа документа',
                'verbose_name_plural': 'Страница заказов документов',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='DocumentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_number', models.BigIntegerField(blank=True, null=True, verbose_name='Номер заказа')),
                ('price', models.PositiveIntegerField(blank=True, default=0, verbose_name='Цена')),
                ('document_type', models.CharField(max_length=255, null=True, verbose_name='Тип документа')),
                ('customer_full_name', models.CharField(max_length=250, verbose_name='Полное имя клиента')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='Номер телефона клиента')),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Электронная почьта клиента')),
                ('customer_message', models.TextField(max_length=1000, verbose_name='Сообщение клиента')),
                ('status', models.IntegerField(choices=[(0, 'ОЖИДАЕТСЯ ПЛАТЕЖ'), (1, 'ДОКУМЕНТ ПРИНЯТ'), (2, 'РАССМАТРИВАЕТЬСЯ'), (3, 'ЗАВЕРШЕННЫЙ'), (4, 'ОТМЕНЕНО')], default=0, verbose_name='Статус')),
                ('file', models.FileField(blank=True, null=True, upload_to='order/document/', verbose_name='Файл')),
                ('expert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Эксперт')),
            ],
            options={
                'verbose_name': 'Заказ документа',
                'verbose_name_plural': 'Заказы документов',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('complaint', models.TextField(verbose_name='Жалоба')),
                ('order_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviceses.documentorder', verbose_name='Заказ документа')),
            ],
            options={
                'verbose_name': 'Жалоба',
                'verbose_name_plural': 'Жалобы',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='MeetingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_number', models.BigIntegerField(blank=True, null=True, verbose_name='Номен заказа')),
                ('customer_full_name', models.CharField(max_length=150, verbose_name='Полное имя клиента')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='Номер телефона клиента')),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Электронная почьта клиента')),
                ('meeting_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Цена встечи')),
                ('language', models.CharField(blank=True, max_length=3, null=True, verbose_name='Язык')),
                ('short_description', models.CharField(blank=True, max_length=255, null=True, verbose_name='краткое описание')),
                ('meeting_status', models.IntegerField(choices=[(0, 'ОЖИДАЕТСЯ ПЛАТЕЖ'), (1, 'ПРИНЯТ'), (2, 'ЗАВЕРШЕННЫЙ'), (3, 'ОТМЕНЕНО')], default=0, verbose_name='Статус встречи')),
                ('meeting_type', models.IntegerField(choices=[(0, 'ЗВОНОК'), (1, 'ВИДЕО ЗВОНОК'), (2, 'ВСТРЕЧА')], verbose_name='Тип встречи')),
                ('meeting_time', models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 15, 12, 45, 42, 947297, tzinfo=datetime.timezone.utc), null=True, verbose_name='Время встречи')),
                ('meeting_end_time', models.TimeField(blank=True, default=serviceses.models.default_meeting_end_time, null=True, verbose_name='Время встречи')),
                ('expert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Эксперт')),
            ],
            options={
                'verbose_name': 'Заказ встречи',
                'verbose_name_plural': 'Заказы встречь',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='MeetingLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location_name', models.CharField(max_length=255, verbose_name='Название локации')),
                ('location_url', models.URLField(verbose_name='Локация url')),
                ('is_send_sms', models.BooleanField(default=False, verbose_name='Смс отправлен')),
                ('meeting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='serviceses.meetingorder', verbose_name='Встреча')),
            ],
            options={
                'verbose_name': 'Локация встречи',
                'verbose_name_plural': 'Локации встреч',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='MeetingLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('link', models.URLField(verbose_name='Ссылка')),
                ('is_send_sms', models.BooleanField(default=False, verbose_name='Смс отправлен')),
                ('meeting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='link', to='serviceses.meetingorder', verbose_name='Встреча')),
            ],
            options={
                'verbose_name': 'Ссылка встречи',
                'verbose_name_plural': 'Ссылки встреч',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='MeetingPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_number', models.CharField(max_length=14, validators=[serviceses.utils.validate_uz_number], verbose_name='Номер телефона')),
                ('full_name', models.CharField(max_length=255, verbose_name='Полное имя')),
                ('is_send_sms', models.BooleanField(default=False, verbose_name='Смс отправлен')),
                ('meeting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='phone', to='serviceses.meetingorder', verbose_name='Встреча')),
            ],
            options={
                'verbose_name': 'Телефонная встреча',
                'verbose_name_plural': 'Телефонные встречи',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ReadyDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_name', models.CharField(max_length=250, verbose_name='Название документа')),
                ('document', models.FileField(upload_to='documents/%Y/%m/%d', verbose_name='Документ')),
                ('document_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviceses.documentorder', verbose_name='Заказ документа')),
            ],
            options={
                'verbose_name': 'Готовый документ',
                'verbose_name_plural': 'Готовые документы',
                'ordering': ('created_at',),
            },
        ),
    ]
