# Generated by Django 5.0.9 on 2024-10-16 17:08

import datetime
import django.db.models.deletion
import serviceses.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingorder',
            name='meeting_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 16, 17, 8, 5, 280275, tzinfo=datetime.timezone.utc), null=True, verbose_name='Время встречи'),
        ),
        migrations.CreateModel(
            name='ServiceEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.IntegerField(validators=[serviceses.utils.validate_rating], verbose_name='Рейтинг')),
                ('description', models.TextField(verbose_name='Описание')),
                ('meeting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='serviceses.meetingorder', verbose_name='Встреча')),
            ],
            options={
                'verbose_name': 'Оценка услуги',
                'verbose_name_plural': 'Оценки услуг',
                'ordering': ('-created_at',),
            },
        ),
    ]
