# Generated by Django 5.1.1 on 2024-09-08 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentcategory',
            name='category_name_ru',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='documentcategory',
            name='category_name_uz',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='document_name_ru',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='document_name_uz',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='meetingorder',
            name='meeting_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
