# Generated by Django 4.2.16 on 2024-10-23 16:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceses', '0002_alter_meetingorder_meeting_time_serviceevaluation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingorder',
            name='meeting_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 23, 16, 29, 23, 480465, tzinfo=datetime.timezone.utc), null=True, verbose_name='Время встречи'),
        ),
    ]
