# Generated by Django 5.1.1 on 2024-09-08 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceses', '0002_documentcategory_category_name_ru_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacts',
            options={'ordering': ('created_at',), 'verbose_name': 'Контракт', 'verbose_name_plural': 'Контракты'},
        ),
        migrations.AlterModelOptions(
            name='documentcategory',
            options={'ordering': ('created_at',), 'verbose_name': 'Категория документа', 'verbose_name_plural': 'Категории документов'},
        ),
        migrations.AlterModelOptions(
            name='documentorder',
            options={'ordering': ('created_at',), 'verbose_name': 'Заказ документа', 'verbose_name_plural': 'Заказы документов'},
        ),
        migrations.AlterModelOptions(
            name='documenttype',
            options={'ordering': ('created_at',), 'verbose_name': 'Тип документа', 'verbose_name_plural': 'Типы документов'},
        ),
        migrations.AlterModelOptions(
            name='meetingorder',
            options={'ordering': ('created_at',), 'verbose_name': 'Заказ встречи', 'verbose_name_plural': 'Заказы встречь'},
        ),
        migrations.AlterField(
            model_name='contacts',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Электронная почьта'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='full_name',
            field=models.CharField(max_length=150, verbose_name='Полное имя'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='message',
            field=models.TextField(max_length=1000, verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='serviceses.documentcategory', verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='documentcategory',
            name='category_name',
            field=models.CharField(max_length=150, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='documentcategory',
            name='category_name_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='documentcategory',
            name='category_name_uz',
            field=models.CharField(max_length=150, null=True, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='documentcategory',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='documentorder',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Электронная почьта клиента'),
        ),
        migrations.AlterField(
            model_name='documentorder',
            name='customer_full_name',
            field=models.CharField(max_length=250, verbose_name='Полное имя клиента'),
        ),
        migrations.AlterField(
            model_name='documentorder',
            name='customer_message',
            field=models.TextField(max_length=1000, verbose_name='Сообщение клиента'),
        ),
        migrations.AlterField(
            model_name='documentorder',
            name='customer_phone',
            field=models.CharField(max_length=20, verbose_name='Номер телефона клиента'),
        ),
        migrations.AlterField(
            model_name='documentorder',
            name='document_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='serviceses.documentcategory', verbose_name='Категория документа'),
        ),
        migrations.AlterField(
            model_name='documentorder',
            name='document_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='serviceses.documenttype', verbose_name='Тип документа'),
        ),
        migrations.AlterField(
            model_name='documentorder',
            name='order_number',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Номер заказа'),
        ),
        migrations.AlterField(
            model_name='documentorder',
            name='status',
            field=models.IntegerField(choices=[(0, 'ОЖИДАЕТСЯ ПЛАТЕЖ'), (1, 'ДОКУМЕНТ ПРИНЯТ'), (2, 'РАССМАТРИВАЕТЬСЯ'), (3, 'ЗАВЕРШЕННЫЙ'), (4, 'ОТМЕНЕНО')], default=0, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='document_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviceses.documentcategory', verbose_name='Категория документа'),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='document_name',
            field=models.CharField(max_length=150, verbose_name='Название документа'),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='document_name_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Название документа'),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='document_name_uz',
            field=models.CharField(max_length=150, null=True, verbose_name='Название документа'),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='meetingorder',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Электронная почьта клиента'),
        ),
        migrations.AlterField(
            model_name='meetingorder',
            name='customer_full_name',
            field=models.CharField(max_length=150, verbose_name='Полное имя клиента'),
        ),
        migrations.AlterField(
            model_name='meetingorder',
            name='customer_phone',
            field=models.CharField(max_length=20, verbose_name='Номер телефона клиента'),
        ),
        migrations.AlterField(
            model_name='meetingorder',
            name='meeting_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена встечи'),
        ),
        migrations.AlterField(
            model_name='meetingorder',
            name='meeting_status',
            field=models.IntegerField(choices=[(0, 'ОЖИДАЕТСЯ ПЛАТЕЖ'), (1, 'ПРИНЯТ'), (2, 'ЗАВЕРШЕННЫЙ'), (3, 'ОТМЕНЕНО')], default=0, verbose_name='Статус встречи'),
        ),
        migrations.AlterField(
            model_name='meetingorder',
            name='meeting_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время встречи'),
        ),
        migrations.AlterField(
            model_name='meetingorder',
            name='meeting_type',
            field=models.IntegerField(choices=[(0, 'ЗВОНОК'), (1, 'ВИДЕО ЗВОНОК'), (2, 'ВСТРЕЧА')], verbose_name='Тип встречи'),
        ),
        migrations.AlterField(
            model_name='meetingorder',
            name='order_number',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Номен заказа'),
        ),
    ]
