# Generated by Django 5.0.9 on 2024-09-11 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceses', '0003_alter_contacts_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadyDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_name', models.CharField(max_length=250)),
                ('document', models.FileField(upload_to='documents/%Y/%m/%d')),
                ('document_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviceses.documentorder')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
