# Generated by Django 4.2.16 on 2024-10-24 15:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceses', '0003_alter_meetingorder_meeting_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentorder',
            name='document_type',
            field=models.TextField(max_length=255, null=True, verbose_name='Краткое описание проблемы'),
        ),
        migrations.AlterField(
            model_name='documentorder',
            name='status',
            field=models.IntegerField(choices=[(0, 'ОЖИДАЕТСЯ'), (1, 'ДОКУМЕНТ ПРИНЯТ'), (2, 'РАССМАТРИВАЕТЬСЯ'), (3, 'ЗАВЕРШЕННЫЙ'), (4, 'ОТМЕНЕНО')], default=0, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='meetingorder',
            name='meeting_status',
            field=models.IntegerField(choices=[(0, 'ОЖИДАЕТСЯ'), (1, 'ПРИНЯТ'), (2, 'ЗАВЕРШЕННЫЙ'), (3, 'ОТМЕНЕНО')], default=0, verbose_name='Статус встречи'),
        ),
        migrations.AlterField(
            model_name='meetingorder',
            name='meeting_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 24, 15, 7, 56, 410841, tzinfo=datetime.timezone.utc), null=True, verbose_name='Время встречи'),
        ),
        migrations.AlterField(
            model_name='meetingorder',
            name='short_description',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Краткое описание проблемы'),
        ),
    ]
