# Generated by Django 5.0.9 on 2024-10-01 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceses', '0004_readydocuments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='readydocuments',
            options={'ordering': ('created_at',), 'verbose_name': 'Готовый документ', 'verbose_name_plural': 'Готовые документы'},
        ),
        migrations.AddField(
            model_name='documentorder',
            name='price',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='readydocuments',
            name='document',
            field=models.FileField(upload_to='documents/%Y/%m/%d', verbose_name='Документ'),
        ),
        migrations.AlterField(
            model_name='readydocuments',
            name='document_name',
            field=models.CharField(max_length=250, verbose_name='Название документа'),
        ),
        migrations.AlterField(
            model_name='readydocuments',
            name='document_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviceses.documentorder', verbose_name='Заказ документа'),
        ),
    ]
