# Generated by Django 5.0.9 on 2024-10-08 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceses', '0005_alter_readydocuments_options_documentorder_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentorder',
            name='order_number',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Номер заказа'),
        ),
        migrations.AlterField(
            model_name='meetingorder',
            name='order_number',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Номен заказа'),
        ),
    ]
