# Generated by Django 5.0.9 on 2024-10-09 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviceses', '0006_alter_documentorder_order_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacts',
            options={'ordering': ('created_at',), 'verbose_name': 'Контакт', 'verbose_name_plural': 'Контакты'},
        ),
    ]
