# Generated by Django 5.0.9 on 2024-10-10 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceses', '0007_alter_contacts_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='contacts/document/'),
        ),
        migrations.AddField(
            model_name='documentorder',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='order/document/'),
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('complaint', models.TextField()),
                ('order_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviceses.documentorder')),
            ],
            options={
                'verbose_name': 'Жалоба',
                'verbose_name_plural': 'Жалобы',
                'ordering': ('created_at',),
            },
        ),
    ]
