# Generated by Django 5.0.9 on 2024-10-11 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceses', '0008_contacts_file_documentorder_file_complaint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Тип'),
        ),
        migrations.RemoveField(
            model_name='documentorder',
            name='document_category',
        ),
        migrations.RemoveField(
            model_name='documenttype',
            name='document_category',
        ),
        migrations.AlterField(
            model_name='documentorder',
            name='document_type',
            field=models.CharField(max_length=255, null=True, verbose_name='Тип документа'),
        ),
        migrations.AddField(
            model_name='meetingorder',
            name='language',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='язык'),
        ),
        migrations.AddField(
            model_name='meetingorder',
            name='short_description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='краткое описание'),
        ),
        migrations.AlterField(
            model_name='meetingorder',
            name='meeting_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Цена встечи'),
        ),
        migrations.DeleteModel(
            name='DocumentCategory',
        ),
        migrations.DeleteModel(
            name='DocumentType',
        ),
    ]
