# Generated by Django 5.0.9 on 2024-10-11 21:33

import datetime
import django.db.models.deletion
import serviceses.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceses', '0010_documentorderpage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualWebsite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_link', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='documentorder',
            name='expert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meetingorder',
            name='expert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meetingorder',
            name='meeting_end_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 11, 22, 3, 0, 694889), null=True, verbose_name='Время встречи'),
        ),
        migrations.AlterField(
            model_name='meetingorder',
            name='meeting_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 11, 21, 33, 0, 694873), null=True, verbose_name='Время встречи'),
        ),
        migrations.CreateModel(
            name='MeetingLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('is_send_sms', models.BooleanField(default=False)),
                ('meeting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='link', to='serviceses.meetingorder')),
            ],
        ),
        migrations.CreateModel(
            name='MeetingLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=255)),
                ('location_url', models.URLField()),
                ('meeting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='serviceses.meetingorder')),
            ],
        ),
        migrations.CreateModel(
            name='MeetingPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=14, validators=[serviceses.utils.validate_uz_number])),
                ('full_name', models.CharField(max_length=255)),
                ('is_send_sms', models.BooleanField(default=False)),
                ('meeting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='phone', to='serviceses.meetingorder')),
            ],
        ),
    ]
