# Generated by Django 5.0.9 on 2024-10-11 21:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceses', '0011_manualwebsite_documentorder_expert_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ManualWebsite',
        ),
        migrations.AlterField(
            model_name='meetingorder',
            name='meeting_end_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 11, 22, 10, 58, 675282), null=True, verbose_name='Время встречи'),
        ),
        migrations.AlterField(
            model_name='meetingorder',
            name='meeting_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 11, 21, 40, 58, 675266), null=True, verbose_name='Время встречи'),
        ),
    ]
