# Generated by Django 5.0.9 on 2024-10-11 22:33

import datetime
import django.db.models.deletion
import serviceses.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceses', '0013_alter_documentorderpage_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meetinglink',
            options={'verbose_name': 'Ссылка встречи', 'verbose_name_plural': 'Ссылки встреч'},
        ),
        migrations.AlterModelOptions(
            name='meetinglocation',
            options={'verbose_name': 'Локация встречи', 'verbose_name_plural': 'Локации встреч'},
        ),
        migrations.AlterModelOptions(
            name='meetingphone',
            options={'verbose_name': 'Телефонная встреча', 'verbose_name_plural': 'Телефонные встречи'},
        ),
        migrations.AlterField(
            model_name='documentorder',
            name='expert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Эксперт'),
        ),
        migrations.AlterField(
            model_name='documentorder',
            name='price',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='meetinglink',
            name='is_send_sms',
            field=models.BooleanField(default=False, verbose_name='Смс отправлен'),
        ),
        migrations.AlterField(
            model_name='meetinglink',
            name='link',
            field=models.URLField(verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='meetinglink',
            name='meeting',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='link', to='serviceses.meetingorder', verbose_name='Встреча'),
        ),
        migrations.AlterField(
            model_name='meetinglocation',
            name='location_name',
            field=models.CharField(max_length=255, verbose_name='Название локации'),
        ),
        migrations.AlterField(
            model_name='meetinglocation',
            name='location_url',
            field=models.URLField(verbose_name='Локация url'),
        ),
        migrations.AlterField(
            model_name='meetinglocation',
            name='meeting',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='serviceses.meetingorder', verbose_name='Встреча'),
        ),
        migrations.AlterField(
            model_name='meetingorder',
            name='expert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Эксперт'),
        ),
        migrations.AlterField(
            model_name='meetingorder',
            name='language',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Язык'),
        ),
        migrations.AlterField(
            model_name='meetingorder',
            name='meeting_end_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 11, 23, 3, 19, 643008), null=True, verbose_name='Время встречи'),
        ),
        migrations.AlterField(
            model_name='meetingorder',
            name='meeting_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 11, 22, 33, 19, 642992), null=True, verbose_name='Время встречи'),
        ),
        migrations.AlterField(
            model_name='meetingphone',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='Полное имя'),
        ),
        migrations.AlterField(
            model_name='meetingphone',
            name='is_send_sms',
            field=models.BooleanField(default=False, verbose_name='Смс отправлен'),
        ),
        migrations.AlterField(
            model_name='meetingphone',
            name='meeting',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='phone', to='serviceses.meetingorder', verbose_name='Встреча'),
        ),
        migrations.AlterField(
            model_name='meetingphone',
            name='phone_number',
            field=models.CharField(max_length=14, validators=[serviceses.utils.validate_uz_number], verbose_name='Номер телефона'),
        ),
    ]
