# Generated by Django 5.0.9 on 2024-10-11 23:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceses', '0016_alter_meetingorder_meeting_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingorder',
            name='meeting_end_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 11, 23, 36, 52, 332500), null=True, verbose_name='Время встречи'),
        ),
        migrations.AlterField(
            model_name='meetingorder',
            name='meeting_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 11, 23, 6, 52, 332481), null=True, verbose_name='Время встречи'),
        ),
    ]
