# Generated by Django 5.0.9 on 2024-10-12 11:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceses', '0017_alter_meetingorder_meeting_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingorder',
            name='meeting_end_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 12, 12, 29, 34, 480690, tzinfo=datetime.timezone.utc), null=True, verbose_name='Время встречи'),
        ),
        migrations.AlterField(
            model_name='meetingorder',
            name='meeting_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 12, 11, 59, 34, 480667, tzinfo=datetime.timezone.utc), null=True, verbose_name='Время встречи'),
        ),
    ]
