# Generated by Django 5.0.9 on 2024-10-14 10:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceses', '0021_meetinglocation_is_send_sms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingorder',
            name='meeting_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 14, 10, 35, 52, 782320, tzinfo=datetime.timezone.utc), null=True, verbose_name='Время встречи'),
        ),
    ]
